### ISSUE TITLE
Permission denied to access property "handleEvent". 

### ISSUE THREAD

**Issue by Patrikkk** [imZack/slack-delete-all-messages#1]
Greetings!  I tried to run your script, and at click event I get the error:
[error] Unexpected Exception: Error: Permission denied to access property "handleEvent". 
I tried googling to find a solution, but didnt find much.
Do you know any workaround?

Using Firefox 3.8 , Selenium IDE 2.9.0

**Comment by imZack** [comment]
@Patrikkk ah, I will check it later

**Comment by zomars** [comment]
I'm having the same issue, I'm using Firefox 41.0a2.

**Comment by greggh** [comment]
Same problem here. I would love to have this working.

**Comment by imZack** [comment]
I have already confirmed this issue, due to slack.com uses bugsnap. I just update the command from **click** to **fireEvent**.

Enjoy it :sparkles:
