### ISSUE TITLE
Element id=batch_delete_link not found

### ISSUE THREAD

**Issue by cairenth** [imZack/slack-delete-all-messages#3]
I'm getting this error:

[info] Executing: |fireEvent | id=batch_delete_link | click |
[error] Element id=batch_delete_link not found

Am I doing something wrong, or is there something that can be changed to make this work again?

**Comment by imZack** [comment]
What's your browser location when you got this error?
It should be something like https://YOUR_SUBDOMAIN.slack.com/archives/general

**Comment by cairenth** [comment]
Yep, I was using the wrong URL. Thanks for setting me straight. Worked beautifully, and I will be sharing it with others who misused their #general channel before realizing its special restrictions.

**Comment by imZack** [comment]
Cool, have a good day! :sparkles:
